# Generated by Django 5.2.7 on 2025-10-19 05:31

import contract.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(blank=True, help_text='Auto-generated contract code', max_length=20, unique=True)),
                ('contract_title', models.CharField(max_length=200)),
                ('vendor_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_terms', models.CharField(choices=[('one_time_payment', 'One Time Payment'), ('installment', 'Installment'), ('milestone_based', 'Milestone Based'), ('others', 'Others')], max_length=50)),
                ('estimated_contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('renewal_terms', models.CharField(choices=[('renewable_fixed', 'Renewable (fixed terms)'), ('not_renewable', 'Not Renewable'), ('on_request', 'On Request')], default='not_renewable', max_length=30)),
                ('scope_of_work', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='For rejected or returned contracts', null=True)),
                ('instructions_for_reviewers', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department')),
                ('department_head', models.ForeignKey(limit_choices_to={'role': 'department_head'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head_contracts', to=settings.AUTH_USER_MODEL)),
                ('legal_officer', models.ForeignKey(limit_choices_to={'role': 'legal_reviewer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_officer_contracts', to=settings.AUTH_USER_MODEL)),
                ('signatory', models.ForeignKey(limit_choices_to={'role': 'signatory'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatory_contracts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contracts', to=settings.AUTH_USER_MODEL)),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contracttype')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contract.models.contract_document_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contract.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='contract.contract')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contract_co_status_601477_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['end_date'], name='contract_co_end_dat_c9055c_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['department'], name='contract_co_departm_14bb62_idx'),
        ),
    ]
